name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ZMK firmware
    strategy:
      fail-fast: false
      matrix:
        include:
          # 左手（Left）のビルド定義
          - board: nice_nano_v2
            shield: bault_left
          # 右手（Right）のビルド定義
          - board: nice_nano_v2
            shield: bault_right
    steps:
      - name: Checkout
        uses: actions/checkout@v4
